version: '3'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    volumes:
        - ./mongo-volume:/data/db

  scraper:
    image: samirettali/pastebin-scraper
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COL=${MONGO_COL}
      - HEALTHCHECK=${HEALTHCHECK}
